# Generated by Django 3.2.18 on 2023-02-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_cookingtimeinminutes_recipes_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('Завтрак', 'Завтрак'), ('Обед', 'Обед'), ('Ужин', 'Ужин')], max_length=200, verbose_name='Название'),
        ),
    ]
