# Generated by Django 3.2.18 on 2023-03-01 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientsamount',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes', verbose_name='Название блюда'),
        ),
    ]
